{"content": {"suites": {"0": {"status": {"total_pass": 5, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 2, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_add_success", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_add_negative", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_add_no_params", "rerun": "0"}, "3": {"status": "FAIL", "message": "   socket.gaierror: [Errno -3] Temporary failure in name resolution\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f201244d550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f201244d550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f201244d550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n", "test_name": "test_fetch", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_fetch_mocks", "rerun": "0"}, "5": {"status": "PASS", "message": "", "test_name": "test_fetch_mocks_failure", "rerun": "0"}, "6": {"status": "FAIL", "message": "   socket.gaierror: [Errno -3] Temporary failure in name resolution\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f201247f390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution\n       urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f201247f390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n       requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f201247f390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n", "test_name": "test_fetch_vcr", "rerun": "0"}}, "suite_name": "test_demo.py"}}}, "date": "April 27, 2023", "start_time": 1682604432.3983152, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "5", "fail": "2", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "7"}